- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
#    - !type:DepartmentTimeRequirement
#      department: Medical
#      time: 10800 # 3 hrs
    - !type:OverallPlaytimeRequirement
      time: 36000 # Frontier - 10 hrs
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  - Brig
  - Maintenance
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: BrigmedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNfsd # Frontier
    outerClothing: ClothingOuterCoatNfsdBomberBrigmed # Frontier
    back: ClothingBackpacknfsdBrigmed # Frontier
    shoes: ClothingShoesBootsNFSDCream # Frontier
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudMedical
    head: ClothingHeadHatNfsdBeretCream # Frontier
    id: NfsdBrigmedic
    ears: ClothingHeadsetNFSDbrown # Frontier
    belt: ClothingBeltMedicalFilled
    pocket1: WeaponPistolMk58Nonlethal # Frontier
    neck: ClothingNeckNfsdSilverBadge # Frontier
  innerClothingSkirt: ClothingUniformJumpskirtNfsd # Frontier
  satchel: ClothingBackpackSatchelnfsdBrigmed # Frontier
  duffelbag: ClothingBackpackDuffelnfsdBrigmed # Frontier
  messenger: ClothingBackpackMessengerBrigmedicFilled # Frontier
