- type: job
  id: Bailiff
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 108000 # Frontier - 30 hours
    - !type:RoleTimeRequirement
      role: JobSeniorOfficer
      time: 21600 # Frontier - 6 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 32400 # 9 hrs
  startingGear: BailiffGear
  icon: "JobIconWarden" # Frontier
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ] # Frontier

- type: startingGear
  id: BailiffGear
  equipment:
    head: ClothingHeadHatNFSDBeretBrown # Frontier
    jumpsuit: ClothingUniformJumpsuitNFSDTacCream # Frontier
    back: ClothingBackpackOfficerFilled # Frontier
    shoes: ClothingShoesBootsNFSDCreamFilled # Frontier
    eyes: ClothingEyesGlassesNFSD # Frontier
    outerClothing: ClothingOuterCoatNFSDFormal # Frontier
    id: NFSDBailiffID # Frontier
    ears: ClothingHeadsetAltNFSDgreen # Frontier
    belt: ClothingBeltNFSDWebbingFilled # Frontier
    pocket1: WeaponPistolMk58Nonlethal
    pocket2: HoloprojectorNFSD # Frontier
    gloves: ClothingHandsGlovesCombatNFSDCream # Frontier
    neck: ClothingNeckNFSDBadgeWarden # Frontier
  innerClothingSkirt: ClothingUniformJumpskirtNFSD # Frontier
  satchel: ClothingBackpackSatchelOfficerFilled # Frontier
  duffelbag: ClothingBackpackDuffelOfficerFilled # Frontier
  messenger: ClothingBackpackMessengerOfficerFilled # Frontier
