- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 21600 # 6 hrs
    - !type:OverallPlaytimeRequirement
      time: 36000 # Frontier - 10 hrs
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic" # Frontier
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  - Brig
  - Maintenance
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: BrigmedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNFSD # Frontier
    outerClothing: ClothingOuterCoatNFSDBomberBrigmed # Frontier
    back: ClothingBackpackNFSDBrigmedFilled # Frontier
    shoes: ClothingShoesBootsNFSDCreamFilled # Frontier
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudNFSDMed # Frontier
    head: ClothingHeadHatNFSDBeretCream # Frontier
    id: NFSDBrigmedicID # Frontier
    ears: ClothingHeadsetNFSDbrown # Frontier
    belt: ClothingBeltNFSDWebbingFilledBrigmedic # Frontier
    neck: ClothingNeckNFSDBadgeSecurityBrigmed # Frontier
    pocket1: WeaponPistolMk58Nonlethal # Frontier
  innerClothingSkirt: ClothingUniformJumpskirtNFSD # Frontier
  satchel: ClothingBackpackSatchelNFSDBrigmedFilled # Frontier
  duffelbag: ClothingBackpackDuffelNFSDBrigmedFilled # Frontier
  messenger: ClothingBackpackMessengerBrigmedicFilled # Frontier
