- type: job
  id: Cadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: JobSecurityCadet
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # Frontier 10 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # Frontier - 10 hrs
      inverted: true # stop playing intern if you're good at security!
  startingGear: CadetGear
  icon: "JobIconSecurityCadet" # Frontier
  supervisors: job-supervisors-security
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service # Frontier
  - External # Frontier
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: CadetGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNFSDShort # Frontier
    back: ClothingBackpackNFSDFilled # Frontier
    shoes: ClothingShoesBootsNFSDBrownFilled # Frontier
    outerClothing: ClothingOuterArmorNFSDArmor # Frontier
    id: NFSDCadetID # Frontier
    ears: ClothingHeadsetNFSDbrown # Frontier
    pocket1: WeaponPistolMk58Nonlethal
    pocket2: BookSecurity
    gloves: ClothingHandsGlovesCombatNFSDBrown # Frontier
    belt: ClothingBeltNFSD # Frontier
    head: ClothingHeadHatNFSDSmallCampaign # Frontier
    eyes: ClothingEyesGlassesNFSD # Frontier
    neck: ClothingNeckNFSDBadgeSecurityCadet # Frontier
  innerClothingSkirt: ClothingUniformJumpskirtNFSDShort # Frontier
  satchel: ClothingBackpackSatchelNFSDFilled # Frontier
  duffelbag: ClothingBackpackDuffelNFSDFilled # Frontier
  messenger: ClothingBackpackMessengerSecurityFilled # Frontier
