- type: job
  id: Deputy
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 43200 # Frontier - 12 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 21600 # Frontier - 6 hrs
  startingGear: DeputyGear
  icon: "JobIconSecurityOfficer" # Frontier
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]

- type: startingGear
  id: DeputyGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNFSD # Frontier
    back: ClothingBackpackNFSDFilled # Frontier
    shoes: ClothingShoesBootsNFSDBrownFilled # Frontier
    eyes: ClothingEyesGlassesNFSD # Frontier
    head: ClothingHeadHatNFSDSmallCampaign # Frontier
    outerClothing: ClothingOuterArmorNFSDArmor # Frontier
    id: NFSDDeputyID # Frontier
    ears: ClothingHeadsetNFSDbrown # Frontier
    belt: ClothingBeltNFSDWebbingFilled # Frontier
    pocket1: WeaponPistolMk58Nonlethal
    gloves: ClothingHandsGlovesCombatNFSDBrown # Frontier
    neck: ClothingNeckNFSDBadgeSecurity # Frontier
  innerClothingSkirt: ClothingUniformJumpskirtNFSD # Frontier
  satchel: ClothingBackpackSatchelNFSDFilled # Frontier
  duffelbag: ClothingBackpackDuffelNFSDFilled # Frontier
  messenger: ClothingBackpackMessengerSecurityFilled # Frontier
