- type: job
  id: PublicAffairsOfficial
  name: job-name-pao
  description: job-description-public-affairs-official
  playTimeTracker: JobPublicAffairsOfficial
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 43200 # Frontier - 12 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10800 # Frontier - 3 hrs
  startingGear: PublicAffairGear
  icon: "JobIconPublicAffairsOfficial" # Frontier
  supervisors: job-supervisors-cadet
  canBeAntag: false
  accessGroups: # Frontier
  - CadetNfsdAccess # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PublicAffairGear
  equipment:
    shoes: ClothingShoesBootsSalvage
    gloves: ClothingHandsGlovesHop
    ears: ClothingHeadsetNfsdBrown # Frontier
    pocket1: HyperlinkBookSpaceLaw
    pocket2: BoxFolderClipboardPao
  storage:
    back:
    - Flash
    - BoxFolderPaoBrown
    - BoxFolderPaoGreen