- type: job
  id: Sheriff
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:WhitelistRequirement
    - !type:OverallPlaytimeRequirement
      time: 129600 # Frontier - 36 hours
    - !type:RoleTimeRequirement
      role: JobSeniorOfficer
      time: 43200 # Frontier - 12 hrs
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 43200 # Frontier - 12 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 43200 # 12 hrs
  weight: 10
  startingGear: SheriffGear
  alwaysUseSpawner: true
  icon: "JobIconHeadOfSecurity" # Frontier
  requireAdminNotify: true
  supervisors: job-supervisors-centcom # Frontier
  whitelistRequired: true
  canBeAntag: false
  access:
  - HeadOfSecurity
  - HeadOfPersonnel # Frontier - This should probably be removed after we confirm they can get into SR office + Bank
  - Command
  - Brig
  - Frontier
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Mercenary # Frontier
  - Bar # Frontier
  - Janitor # Frontier
  - Theatre # Frontier
  - Kitchen # Frontier
  - Chapel # Frontier
  - Hydroponics # Frontier
  - Chemistry # Frontier
  - Engineering # Frontier
  - Quartermaster # Frontier
  - Research # Frontier
  - Salvage # Frontier
  - Cargo # Frontier
  - Atmospherics # Frontier
  - Medical # Frontier
  - EmergencyShuttleRepealAll # Frontier
  - Captain # Frontier
  - ChiefEngineer # Frontier
  - ChiefMedicalOfficer # Frontier
  - ResearchDirector # Frontier
  - Pilot # Frontier
  - Lawyer # Frontier
  - Cryogenics # Frontier
  - Mail # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: SheriffGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitNFSDTacGray # Frontier
    back: ClothingBackpackNFSDsheriffFilled # Frontier
    shoes: ClothingShoesBootsNFSDBrownFilled # Frontier
    outerClothing: ClothingOuterCoatNFSDFormalSheriff # Frontier
    eyes: ClothingEyesGlassesNFSD # Frontier
    head: ClothingHeadHatNFSDCampaignFilled # Frontier
    id: NFSDSheriffID # Frontier
    mask: ClothingMaskGasSheriff # Frontier
    gloves: ClothingHandsGlovesCombatNFSDCream # Frontier
    ears: ClothingHeadsetAltNFSDCreamandBrown # Frontier
    belt: ClothingBeltNFSDWebbingFilled # Frontier
    pocket1: WeaponPistolMk58Nonlethal
    pocket2: HoloprojectorNFSD # Frontier
    neck: ClothingNeckMantleSheriffFilled # Frontier
    suitstorage: WeaponEnergyGunMultiphase # Frontier - DeltaV gun
  innerClothingSkirt: ClothingUniformJumpskirtNFSD # Frontier
  satchel: ClothingBackpackSatchelNFSDsheriffFilled # Frontier
  duffelbag: ClothingBackpackDuffelNFSDsheriffFilled # Frontier
  messenger: ClothingBackpackMessengerHOSFilled # Frontier
